using CortexBridge.Api.Auth;
using CortexBridge.Api.Common;
using CortexBridge.Api.Data;
using CortexBridge.Api.Data.Entities;
using CortexBridge.Api.Sessions;
using CortexBridge.Api.Tmux;
using Microsoft.EntityFrameworkCore;

namespace CortexBridge.Api.Endpoints;

/// <summary>
/// Start a FRESH claude session for the project - no <c>--resume</c>, a brand
/// new sessionUuid generated by CC on first record write. Counterpart of
/// <see cref="ActivateEndpoint"/> (which resumes a specific known UID) and
/// <c>/restart</c> (which resumes the last UID if found). Use when the user
/// taps "+ New Session" expecting to start over.
///
/// Atomic graceful sequence (kill+spawn in one operation):
///   1. Reject if owner=Pc (ADR-017: bridge cannot terminate Anthropic ext).
///   2. If a tmux window exists, /exit gracefully (Esc -> /exit -> poll 3s ->
///      kill-window backstop). Same proven pattern as Handoff/Activate/Exit.
///   3. Clear session_ownership row -> Owner.None (the new session will create
///      its own when claude writes its first record + the user explicitly
///      switches owner via a later interaction).
///   4. Spawn `claude` (no --resume) in the project workspace dir.
///   5. Audit session.new.
/// </summary>
public static class NewSessionEndpoint
{
    public static void MapNewSession(this IEndpointRouteBuilder app)
    {
        app.MapPost("/api/sessions/{projectId}/new", NewHandler);
    }

    private static async Task<IResult> NewHandler(
        string projectId,
        HttpContext ctx,
        BridgePaths paths,
        TmuxClient tmux,
        SessionScanner scanner,
        SessionOwnershipRegistry ownership,
        SessionStateRegistry state,
        BridgeDbContext db,
        ILoggerFactory loggerFactory,
        CancellationToken ct)
    {
        var log = loggerFactory.CreateLogger("NewSession");

        // Path validation mirroring RestartEndpoint - projectId must be a
        // single dir name; full path must stay under WorkspaceRoot.
        if (projectId.Contains('/') || projectId.Contains('\\') || projectId.Contains(".."))
            return ResultsHelpers.Error(400, "project.bad_id",
                "projectId must be a single directory name");
        var workspaceDir = Path.Combine(paths.WorkspaceRoot, projectId);
        var resolved = Path.GetFullPath(workspaceDir);
        var rootResolved = Path.GetFullPath(paths.WorkspaceRoot);
        if (!resolved.StartsWith(rootResolved + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && resolved != rootResolved)
        {
            return ResultsHelpers.Error(400, "project.escape", "Path escapes workspace root");
        }
        if (!Directory.Exists(workspaceDir))
            return ResultsHelpers.Error(404, "project.not_found",
                $"Workspace directory '{projectId}' not found in {paths.WorkspaceRoot}");

        // ADR-017: bridge cannot terminate Anthropic ext - hard-refuse same as
        // RestartEndpoint/ActivateEndpoint/ExitEndpoint.
        var (owner, _, _) = await ownership.ResolveAsync(projectId, db, tmux, scanner, ct);
        if (owner == SessionOwnershipRegistry.Owner.Pc)
        {
            await Audit(db, ctx.GetAuthToken(), projectId, null,
                "session.new", "denied", "owned_by_pc", ct);
            return ResultsHelpers.Error(409, "new.owned_by_pc",
                "Session is on PC (Mode B). The bridge cannot start a new "
                + "session while PC owns it. Close VS Code workspace first.");
        }

        // Graceful exit of any existing window (proven pattern).
        if (await tmux.WindowExistsAsync(projectId, ct))
        {
            try
            {
                try { await tmux.SendKeyAsync(projectId, "Escape", ct); }
                catch (TmuxException) { /* nothing to dismiss */ }
                await tmux.SendKeysAsync(projectId, "/exit", ct);
                await tmux.SendKeyAsync(projectId, "Enter", ct);
            }
            catch (TmuxException ex)
            {
                log.LogWarning(ex, "New: /exit injection failed for {Project}", projectId);
            }
            var deadline = DateTime.UtcNow.AddSeconds(3);
            while (DateTime.UtcNow < deadline
                   && await tmux.WindowExistsAsync(projectId, ct))
            {
                await Task.Delay(TimeSpan.FromMilliseconds(250), ct);
            }
            if (await tmux.WindowExistsAsync(projectId, ct))
            {
                log.LogInformation(
                    "New: tmux window {Project} did not exit after /exit, forcing kill",
                    projectId);
                await tmux.KillWindowAsync(projectId, ct);
            }
        }

        // Clear ownership row - new session will create its own row via the
        // first hook (or stay Owner.None until user explicitly activates).
        var row = await db.SessionOwnerships
            .FirstOrDefaultAsync(x => x.ProjectId == projectId, ct);
        if (row is not null)
        {
            db.SessionOwnerships.Remove(row);
            await db.SaveChangesAsync(ct);
        }
        // Clear in-memory state too.
        state.SetProcessing(projectId, false);
        state.SetNeedsInput(projectId, false);

        // Spawn fresh claude (no --resume).
        try
        {
            await tmux.NewWindowAsync(projectId, workspaceDir, "claude", ct);
        }
        catch (TmuxException ex)
        {
            log.LogError(ex, "Failed to start fresh claude for {Project}", projectId);
            await Audit(db, ctx.GetAuthToken(), projectId, null,
                "session.new", "error", ex.Message, ct);
            return ResultsHelpers.Error(500, "tmux.new_window_failed", ex.Message);
        }

        await Audit(db, ctx.GetAuthToken(), projectId, null,
            "session.new", "ok", "fresh", ct);

        return Results.Json(
            new { acceptedAt = DateTimeOffset.UtcNow.ToString("o") },
            Json.Default, statusCode: 202);
    }

    private static async Task Audit(
        BridgeDbContext db, BearerToken? token, string projectId, string? sessionUuid,
        string action, string result, string? detail, CancellationToken ct)
    {
        db.AuditLogs.Add(new AuditLog
        {
            Timestamp = DateTimeOffset.UtcNow,
            ProjectId = projectId,
            SessionUuid = sessionUuid,
            Action = action,
            TokenId = token?.Id,
            Result = result,
            Detail = detail,
        });
        await db.SaveChangesAsync(ct);
    }
}
